### ISSUE TITLE
HOW TO GUİLD ID 

### ISSUE THREAD

**Issue by Sercedes001** [002-sans/Dm-All#1]

**Comment by 002-sans** [comment]
what's the problem ?

**Comment by Sercedes001** [comment]
it want to me guild id

**Comment by 002-sans** [comment]
what's that language bro ?

**Comment by 002-sans** [comment]
with more details it will be better

**Comment by Sercedes001** [comment]
What is Guild Id? can you answer this first?

**Comment by 002-sans** [comment]
`Settings -> Advenced -> Developer Mode` in discord

**Comment by Sercedes001** [comment]
is it your own id?

**Comment by 002-sans** [comment]
let's check [that](https://stackoverflow.com/questions/62021707/what-is-guild-id-in-discord)
